version: "3.8"
services:
  mysqldb:
    container_name: mysqldb
    image: mysql:8.0.29
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: student_information
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db:/var/lib/mysql


  frontend: 
    container_name: frontend
    restart: always
    depends_on:
      - mysqldb
    build: ./frontend
    ports:
      - "3000:3000"
    links:
      - backend


  backend:
    build: ./backend
    container_name: backend
    restart: on-failure
    ports:
      - 8090:8090
    depends_on:
      - mysqldb
volumes:
  db: